#!/usr/bin/env bash
#
# One-shot installer for claude4nblm on an Ubuntu/Debian VPS (e.g. Hostinger).
# Automates: system deps → venv + install → .env → NotebookLM auth check → systemd.
#
# Run it from inside the cloned repo:
#   git clone https://github.com/smartcib2025/Claude4nblm.git /opt/claude4nblm
#   cd /opt/claude4nblm && git checkout claude/notebooklm-telegram-mobile-waoecu
#   bash scripts/setup_vps.sh
#
# The script is interactive; it prompts for the values it needs and never echoes
# secrets. Re-running it is safe: it keeps an existing .env unless you say otherwise.

set -euo pipefail

# --- helpers ---------------------------------------------------------------
c_bold=$'\033[1m'; c_green=$'\033[32m'; c_yellow=$'\033[33m'; c_red=$'\033[31m'; c_reset=$'\033[0m'
info()  { printf '%s\n' "${c_bold}==>${c_reset} $*"; }
ok()    { printf '%s\n' "${c_green}✓${c_reset} $*"; }
warn()  { printf '%s\n' "${c_yellow}!${c_reset} $*"; }
err()   { printf '%s\n' "${c_red}✗${c_reset} $*" >&2; }
ask()   { local p="$1" d="${2:-}" v; if [ -n "$d" ]; then read -r -p "$p [$d]: " v || true; printf '%s' "${v:-$d}"; else read -r -p "$p: " v || true; printf '%s' "$v"; fi; }
ask_secret() { local p="$1" v; read -r -s -p "$p: " v || true; printf '\n' >&2; printf '%s' "$v"; }

# Run a command as root whether or not we're already root.
SUDO=""
if [ "$(id -u)" -ne 0 ]; then
    if command -v sudo >/dev/null 2>&1; then SUDO="sudo"; else
        warn "Not root and 'sudo' not found — system-package and systemd steps may be skipped."
    fi
fi

# --- locate repo root ------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$REPO_ROOT"
if [ ! -f "pyproject.toml" ]; then
    err "pyproject.toml not found in $REPO_ROOT — run this from inside the cloned repo."
    exit 1
fi
info "Repo root: $REPO_ROOT"

# --- 1. system dependencies -----------------------------------------------
info "Step 1/5 — system dependencies (python3, venv, git)"
if command -v apt-get >/dev/null 2>&1; then
    $SUDO apt-get update -qq
    $SUDO apt-get install -y -qq python3 python3-venv python3-pip git
    ok "System packages ready"
else
    warn "apt-get not found — ensure python3 (3.10+), python3-venv and git are installed."
fi

# --- 2. virtualenv + install ----------------------------------------------
info "Step 2/5 — Python virtualenv + install"
if [ ! -d ".venv" ]; then
    python3 -m venv .venv
    ok "Created .venv"
fi
./.venv/bin/pip install -q --upgrade pip
./.venv/bin/pip install -q -e .
ok "Installed claude4nblm and dependencies"
VENV_PY="$REPO_ROOT/.venv/bin/python"
VENV_NBLM="$REPO_ROOT/.venv/bin/notebooklm"

# --- 3. .env configuration -------------------------------------------------
info "Step 3/5 — configuration (.env)"
ENV_FILE="$REPO_ROOT/.env"
WRITE_ENV=1
if [ -f "$ENV_FILE" ]; then
    ans="$(ask "An .env already exists. Overwrite it? (y/N)" "N")"
    case "$ans" in [yY]*) WRITE_ENV=1 ;; *) WRITE_ENV=0; warn "Keeping existing .env" ;; esac
fi

if [ "$WRITE_ENV" -eq 1 ]; then
    echo
    echo "Enter the required values (input for secrets is hidden):"
    C4N_TELEGRAM="$(ask_secret '  Telegram bot token (from @BotFather)')"
    C4N_ANTHROPIC="$(ask_secret '  Anthropic API key (console.anthropic.com)')"
    C4N_CHATIDS="$(ask '  Allowed Telegram chat IDs (comma-separated, blank to pair later)' '')"
    C4N_NOTEBOOK="$(ask '  Default NotebookLM notebook id (optional)' '')"
    echo
    echo "  NotebookLM auth: log in on your laptop with 'notebooklm login', then either"
    echo "  (A) copy storage_state.json to ~/.notebooklm/profiles/default/ on this server, or"
    echo "  (B) give a local path here to embed it into .env now."
    C4N_AUTH_PATH="$(ask '  Path to a storage_state.json to embed (blank for option A)' '')"

    C4N_AUTH_JSON=""
    if [ -n "$C4N_AUTH_PATH" ]; then
        if [ -f "$C4N_AUTH_PATH" ]; then
            C4N_AUTH_JSON="$("$VENV_PY" -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1]))))' "$C4N_AUTH_PATH")"
            ok "Embedded storage_state.json into NOTEBOOKLM_AUTH_JSON"
        else
            warn "File not found: $C4N_AUTH_PATH — skipping (use option A instead)."
        fi
    fi

    # Write .env safely via Python (handles special characters in tokens/JSON).
    C4N_TELEGRAM="$C4N_TELEGRAM" C4N_ANTHROPIC="$C4N_ANTHROPIC" \
    C4N_CHATIDS="$C4N_CHATIDS" C4N_NOTEBOOK="$C4N_NOTEBOOK" \
    C4N_AUTH_JSON="$C4N_AUTH_JSON" C4N_WORKDIR="$REPO_ROOT" \
    "$VENV_PY" - "$ENV_FILE" <<'PY'
import os, sys
path = sys.argv[1]
lines = [
    "# Generated by scripts/setup_vps.sh",
    f"TELEGRAM_BOT_TOKEN={os.environ['C4N_TELEGRAM']}",
    f"ANTHROPIC_API_KEY={os.environ['C4N_ANTHROPIC']}",
    f"ALLOWED_CHAT_IDS={os.environ['C4N_CHATIDS']}",
    "ALLOWLIST_PATH=./state/allowlist.json",
    f"WORKDIR={os.environ['C4N_WORKDIR']}",
    f"NOTEBOOKLM_NOTEBOOK={os.environ['C4N_NOTEBOOK']}",
]
auth = os.environ.get("C4N_AUTH_JSON", "")
if auth:
    lines.append(f"NOTEBOOKLM_AUTH_JSON={auth}")
with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
PY
    chmod 600 "$ENV_FILE"
    ok "Wrote $ENV_FILE (permissions 600)"
fi

# --- 4. NotebookLM auth check ---------------------------------------------
info "Step 4/5 — NotebookLM auth check"
# Run 'notebooklm list' with .env loaded via python-dotenv (NOT bash `source`,
# which would mangle the raw-JSON NOTEBOOKLM_AUTH_JSON value).
if "$VENV_PY" - "$ENV_FILE" "$VENV_NBLM" <<'PY'
import os, subprocess, sys
from dotenv import dotenv_values
env = dict(os.environ)
env.update({k: v for k, v in dotenv_values(sys.argv[1]).items() if v is not None})
sys.exit(subprocess.run([sys.argv[2], "list"], env=env,
                        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode)
PY
then
    ok "NotebookLM authenticated — 'notebooklm list' works"
else
    warn "Could not list NotebookLM notebooks yet."
    warn "Log in on your laptop ('notebooklm login') and copy storage_state.json to:"
    warn "  ~/.notebooklm/profiles/default/storage_state.json"
    warn "or set NOTEBOOKLM_AUTH_JSON in $ENV_FILE, then re-run this script."
fi

# --- 5. systemd service ----------------------------------------------------
info "Step 5/5 — systemd service (24/7)"
SERVICE_USER="${SUDO_USER:-$(id -un)}"
if [ -z "$SUDO" ] && [ "$(id -u)" -ne 0 ]; then
    warn "No root privileges — skipping systemd. To run manually:"
    echo "    $VENV_PY -m claude4nblm"
else
    ans="$(ask "Install and start a systemd service now? (Y/n)" "Y")"
    case "$ans" in
        [nN]*) warn "Skipped systemd. Run manually: $VENV_PY -m claude4nblm" ;;
        *)
            UNIT=/etc/systemd/system/claude4nblm.service
            $SUDO tee "$UNIT" >/dev/null <<EOF
[Unit]
Description=claude4nblm Telegram <-> Claude Code + NotebookLM bridge
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$REPO_ROOT
ExecStart=$VENV_PY -m claude4nblm
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
            $SUDO systemctl daemon-reload
            $SUDO systemctl enable --now claude4nblm
            ok "Service installed and started (User=$SERVICE_USER)"
            echo "    Follow logs: ${c_bold}journalctl -u claude4nblm -f${c_reset}"
            ;;
    esac
fi

# --- done ------------------------------------------------------------------
echo
ok "Setup complete."
if [ -z "${C4N_CHATIDS:-}" ] && ! grep -q '^ALLOWED_CHAT_IDS=.\+' "$ENV_FILE" 2>/dev/null; then
    echo
    warn "You did not set ALLOWED_CHAT_IDS. To authorize your phone:"
    echo "  1) Message your bot 'hi' in Telegram."
    echo "  2) Find the chat id in the logs: journalctl -u claude4nblm | grep 'Pairing requested'"
    echo "  3) Put it in $ENV_FILE (ALLOWED_CHAT_IDS=<id>) and: sudo systemctl restart claude4nblm"
fi
echo
echo "From your phone, message the bot, e.g.: ${c_bold}list my notebooks${c_reset}"
